# Generated by Django 5.2 on 2025-05-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scope1', models.IntegerField()),
                ('scope2', models.IntegerField()),
                ('scope3', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('pdfname', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
